// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewWorkspace struct {
	Name     string `json:"name"`
	IsPublic bool   `json:"is_public"`
	UserID   string `json:"user_id"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID        string `json:"id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	IsActive  bool   `json:"is_active"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Workspace struct {
	ID                string   `json:"id"`
	Name              string   `json:"name"`
	IsActive          bool     `json:"is_active"`
	IsPublic          bool     `json:"is_public"`
	Owner             *User    `json:"owner"`
	Collaborators     []*User  `json:"collaborators"`
	ExcalidrawObjects []string `json:"excalidraw_objects"`
	CreatedAt         string   `json:"created_at"`
	UpdatedAt         string   `json:"updated_at"`
}
